env:
  global:
  - CC_TEST_REPORTER_ID=1561686e6399317b53a92aaad0550f8b91fe5af312e1f2852ab803ff6fcb6fa9
language: python
matrix:
  include:
  - python: "3.6"
    dist: xenial
    env:
      TEST_REPORT_TARGET: "yes"
  - python: "3.7"
    dist: xenial
  - python: "3.8-dev"
    dist: xenial
install:
  - pip install pipenv
  - pipenv install --dev --skip-lock
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - pipenv run py.test -v --cov-report=xml --cov=. tests/
  - '[ $TEST_REPORT_TARGET ] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT || echo "Skip send test report"'
notifications:
  slack:
    secure: DnVG8IgIoS3C2Z/xB83tKfRE1tgRXHO7A6QDzkB+axsKxYx88Wl2dz5YJiMsHMeTueRv7mldi8haWCTVgPrz2Mz+vXDqr5K0d/YUQ1bXgtVwG/K/eQ679FF8yjykugPknGerDiW1j+ITT6wwDb6SiZRKailWTZJLKQK+um52UWw=
