env:
  global:
  - CC_TEST_REPORTER_ID=1561686e6399317b53a92aaad0550f8b91fe5af312e1f2852ab803ff6fcb6fa9
language: python
matrix:
  include:
  - python: "3.6"
    dist: xenial
  - python: "3.7"
    dist: xenial
    env:
      TEST_REPORT_TARGET: "yes"
install:
  - pip install pipenv
  - pipenv install --dev --skip-lock
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - make test
  - '[ $TEST_REPORT_TARGET ] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT || echo "Skip send test report"'
notifications:
  slack:
    secure: R2lrYvohHtXpznOK1XreP6Uhs8xTSdoGfd1Wsq1mPSgpZ8vWgjeyy0f2izrVhyl8+l91sjrP388mGqMvzD8zrYb09DxOYnYmTe2j6Ta5oRzCPBQub+9/l0jqHGj8s05TGgcQKEij8oXjyrj7ymIdF0zalS60qokjqWwDrT5eQvg=
