site_name: Jumeaux
site_author: tadashi-aikawa
repo_name: tadashi-aikawa/jumeaux
repo_url: https://github.com/tadashi-aikawa/jumeaux
edit_uri: edit/master/docs/
site_favicon: 'images/favicon.ico'
strict: true

pages:
  - Home: index.md
  - Get Started:
    - Quickstart: getstarted/quickstart.md
    - Report: getstarted/report.md
    - Configuration: getstarted/configuration.md
  - Addons:
    - Summary: ja/addons/index.md
    - log2reqs: ja/addons/log2reqs.md
    - reqs2reqs(TODO): todo.md
    - res2res: ja/addons/res2res.md
    - res2dict: ja/addons/res2dict.md
    - judgement: ja/addons/judgement.md
    - store_criterion: ja/addons/store_criterion.md
    - dump: ja/addons/dump.md
    - did_challenge: ja/addons/did_challenge.md
    - final: ja/addons/final.md
  - Models:
    - RequestCondition: models/request-condition.md

theme: material

extra:
  logo: 'images/logo.png'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: tadashi-aikawa
  social:
    - type: github-alt
      link: https://github.com/tadashi-aikawa
  feature:
    tabs: true


markdown_extensions:
    - meta
    # fontawesomeのアイコン
    - fontawesome_markdown
    # 内部参照
    - wikilinks
    # 改行が2spaceじゃなくてもOK
    - nl2br
    # warningとか
    - admonition
    # 注釈
    - footnotes
    # コードのsyntax
    - markdown.extensions.codehilite(guess_lang=false)
    # 見出しに逆リンクを貼れる
    - markdown.extensions.toc(permalink=true)
    # expandableにする
    - pymdownx.details
    # 絵文字対応
    - pymdownx.emoji
    # HTMLやemailをリンク化
    - pymdownx.magiclink
    # 別のmarkdownファイルを埋め込み可能
    - pymdownx.snippets:
        base_path: docs
    # indentされた中でのcode blockとか
    - pymdownx.superfences

extra_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
    - 'css/custom.css'
