site_name: Jumeaux
site_author: tadashi-aikawa

docs_dir: mkdocs
site_dir: docs
strict: true

repo_name: tadashi-aikawa/jumeaux
repo_url: https://github.com/tadashi-aikawa/jumeaux
edit_uri: edit/master/mkdocs/

pages:
  - Home: index.md
  - Get Started:
    - Quickstart: ja/getstarted/quickstart.md
    - Report: ja/getstarted/report.md
    - Configuration: ja/getstarted/configuration.md
  - Addons:
    - Summary: ja/addons/index.md
    - log2reqs: ja/addons/log2reqs.md
    - reqs2reqs: ja/addons/reqs2reqs.md
    - res2res: ja/addons/res2res.md
    - res2dict: ja/addons/res2dict.md
    - judgement: ja/addons/judgement.md
    - store_criterion: ja/addons/store_criterion.md
    - dump: ja/addons/dump.md
    - did_challenge: ja/addons/did_challenge.md
    - final: ja/addons/final.md
  - Models:
    - AccessPoint: ja/models/access-point.md
    - Notifier: ja/models/notifier.md
    - Request: ja/models/request.md
    - RequestCondition: ja/models/request-condition.md
  - Releases: ja/releases/index.md

theme:
  name: material
  logo: 'img/logo.png'
  favicon: 'img/favicon.ico'
  feature:
    tabs: false

extra:
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: tadashi-aikawa
  social:
    - type: github-alt
      link: https://github.com/tadashi-aikawa
  search:
    language: 'en, jp'


markdown_extensions:
    - meta
    # fontawesomeのアイコン
    - fontawesome_markdown
    # 内部参照
    - wikilinks
    # 改行が2spaceじゃなくてもOK
    - nl2br
    # warningとか
    - admonition
    # 注釈
    - footnotes
    # コードのsyntax
    - codehilite:
        guess_lang: false
    # 見出しに逆リンクを貼れる
    - markdown.extensions.toc(permalink=true)
    # expandableにする
    - pymdownx.details
    # 絵文字対応
    - pymdownx.emoji
    # HTMLやemailをリンク化
    - pymdownx.magiclink
    # 別のmarkdownファイルを埋め込み可能
    - pymdownx.snippets:
        base_path: mkdocs
    # indentされた中でのcode blockとか
    - pymdownx.superfences

extra_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
    - 'css/custom.css'
