one:
  name: one
  host: http://localhost/api/simple/one
other:
  name: other
  host: http://localhost/api/simple/other
addons:
  final:
    - name: jumeaux.addons.final.aws
      config:
        table: jumeaux-viewer
        bucket: mamansoft-jumeaux-viewer
        cache_max_age: 120
        checklist: sample
        local_stack:
          use: true
