title: DEMO  # Ignore if you specified `--title` [default: no title]
threads: 1  # Ignore if you specified `--threads` [default: 1]
one:
  name: jumeaux
  host: https://api.github.com/repos/tadashi-aikawa/jumeaux
other:
  name: owlmixin
  host: https://api.github.com/repos/tadashi-aikawa/owlmixin
output:
  encoding: utf8
  response_dir: responses
  logger:  # (See http://wingware.com/psupport/python-manual/3.4/library/logging.config.html#logging-config-dictschema)
    version: 1
    formatters:
      simple:
        format: '%(levelname)s %(message)s'
    handlers:
      console:
        class : logging.StreamHandler
        formatter: simple
        level   : INFO
        stream  : ext://sys.stderr
    root:
      level: INFO
      handlers: [console]
addons:
  log2reqs:
    name: jumeaux.addons.log2reqs.csv
    config:
      encoding: utf8
  store_criterion:
    - name: jumeaux.addons.store_criterion.general
      config:
        statuses:
          - different
  dump:
    - name: jumeaux.addons.dump.json
