one:
  name: one
  host: http://localhost/api/simple/one
other:
  name: other
  host: http://localhost/api/simple/other
addons:
  final:
    - name: miroir
      config:
        table: miroir
        bucket: mamansoft-miroir
        cache_max_age: 120
        checklist: sample
        local_stack:
          use: true
